import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://hoobake.com/login?redirectPath=%2Fdashboard%2Fcustomer%2Fprofile');
  await page.getByRole('textbox', { name: 'youremail@email.com' }).click();
  await page.getByRole('textbox', { name: 'youremail@email.com' }).fill('magif69413@bialode.com');
  await page.getByText('Email PasswordRemember').click();
  await page.getByRole('textbox', { name: '******' }).click();
  await page.getByRole('textbox', { name: '******' }).fill('12345678Tar!');
  await page.getByRole('button', { name: 'Log In', exact: true }).click();
  await page.getByRole('link', { name: 'AI Bot' }).click();
  await page.getByRole('textbox', { name: 'Chat with Hoobake' }).click();
  await page.getByRole('textbox', { name: 'Chat with Hoobake' }).fill('hello');
  await page.getByRole('textbox', { name: 'Chat with Hoobake' }).press('Enter');
  await page.locator('form').getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('textbox', { name: 'Chat with Hoobake' }).click();
  await page.getByRole('textbox', { name: 'Chat with Hoobake' }).fill('Birthday');
  await page.getByRole('textbox', { name: 'Chat with Hoobake' }).press('Enter');
  await page.locator('.p-4.bg-linear-to-r').click();
  await page.getByRole('textbox', { name: 'Chat with Hoobake' }).click();
  await page.getByRole('textbox', { name: 'Chat with Hoobake' }).fill('cake');
  await page.locator('.p-4.bg-linear-to-r').click();
  await page.getByRole('textbox', { name: 'Chat with Hoobake' }).click();
  await page.getByRole('textbox', { name: 'Chat with Hoobake' }).fill('chocolate');
  await page.getByRole('textbox', { name: 'Chat with Hoobake' }).press('Enter');
  await page.locator('.p-4.bg-linear-to-r').click();
  await page.getByRole('textbox', { name: 'Chat with Hoobake' }).click();
  await page.getByRole('textbox', { name: 'Chat with Hoobake' }).fill('10');
  await page.locator('.p-4.bg-linear-to-r').click();
  await page.getByRole('textbox', { name: 'Chat with Hoobake' }).click();
  await page.getByRole('textbox', { name: 'Chat with Hoobake' }).fill('floral');
  await page.locator('.p-4.bg-linear-to-r').click();
  await page.getByRole('textbox', { name: 'Chat with Hoobake' }).click();
  await page.getByRole('textbox', { name: 'Chat with Hoobake' }).fill('16th december');
  await page.getByRole('textbox', { name: 'Chat with Hoobake' }).press('Enter');
  await page.locator('.p-4.bg-linear-to-r').click();
  await page.getByRole('textbox', { name: 'Chat with Hoobake' }).click();
  await page.getByRole('textbox', { name: 'Chat with Hoobake' }).fill('at 7 pm');
  await page.locator('.p-4.bg-linear-to-r').click();
  await page.getByRole('textbox', { name: 'Chat with Hoobake' }).click();
  await page.getByRole('textbox', { name: 'Chat with Hoobake' }).fill('Delivery');
  await page.locator('.p-4.bg-linear-to-r').click();
  await page.getByRole('textbox', { name: 'Chat with Hoobake' }).click();
  await page.getByRole('textbox', { name: 'Chat with Hoobake' }).fill('Chicago, Ca 9001');
  await page.locator('.p-4.bg-linear-to-r').click();
  await page.getByText('Danchaq LTDLos Angels, United States📍 Location: https://hoobake.com/dashboard/').click();
  await page.getByRole('button', { name: 'Contact With Me' }).click();
  await page.getByRole('button', { name: 'Generate With AI' }).click();
  await page.getByRole('button').nth(3).click();
  await page.getByRole('button', { name: 'New Chat' }).nth(1).click();
  await page.getByText('Chicago, USA').first().click();
  await page.getByRole('button', { name: 'Contact With Me' }).click();
  await page.getByRole('button', { name: 'Generate With AI' }).click();
  await page.getByRole('button', { name: 'Message' }).click();
  await page.getByRole('textbox', { name: 'Type a message...' }).click();
  await page.getByRole('textbox', { name: 'Type a message...' }).fill('hello ');
  await page.getByRole('textbox', { name: 'Type a message...' }).press('Enter');
});